<!--JavaScriptはエラーをスローします
エラーが発生すると、JavaScriptは通常停止し、エラーメッセージを生成します。

これの専門用語は次のとおりです。JavaScriptは例外をスローします（エラーをスローします）。

JavaScriptは、実際には、nameとmessageの2つのプロパティを持つErrorオブジェクトを 作成します。

スローステートメント
このthrowステートメントを使用すると、カスタムエラーを作成できます。

技術的には、例外をスローする（エラーをスローする）ことができます。

例外は、JavaScript String、a Number、a、BooleanまたはObject：です。

throw "Too big";    // throw a text
throw 500;          // throw a number
およびとthrow一緒に使用するtryと catch、プログラムフローを制御し、カスタムエラーメッセージを生成できます。-->

<!--入力検証の例
この例では、入力を調べます。値が間違っていると、例外（err）がスローされます。
例外（err）がcatchステートメントによってキャッチされ、カスタムエラーメッセージが表示されます。-->

<!DOCTYPE html>
<html>
<body>

<h2>JavaScript try catch</h2>

<p>Please input a number between 5 and 10:</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="p01"></p>

<script>
function myFunction() {
  const message = document.getElementById("p01");
  message.innerHTML = "";
  let x = document.getElementById("demo").value;
  try { 
    if(x == "")  throw "empty";
    if(isNaN(x)) throw "not a number";
    x = Number(x);
    if(x < 5)  throw "too low";
    if(x > 10)   throw "too high";
  }
  catch(err) {
    message.innerHTML = "Input is " + err;
  }
}
</script>

</body>
</html>



